# Generated by Django 6.1.1 on 2026-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombre_completo", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=50)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "telefono",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
