# Generated by Django 6.1.1 on 2026-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=8, unique=True)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('anio', models.IntegerField()),
                ('kilometraje', models.IntegerField(default=0)),
                ('combustible', models.CharField(max_length=15)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad_pasajeros', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
